application: edemsignups
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail_bounce
- mail

handlers:
- url: /_ah/bounce
  script: bounce_handler.app
  login: admin

- url: /_ah/mail/optout@edemsignups\.appspotmail\.com
  script: optout_handler.app
  login: admin

- url: /optout
  script: optout_page.app

- url: /.*
  script: controller.app
  login: admin

